### ISSUE TITLE
is there a docker image for oo 6.4 version?

### ISSUE THREAD

**Issue by beeant0512** [aleho/onlyoffice-ce-docker-license#29] opened 2021-09-20 15:15 UTC

**Comment by aleho** [comment] 2021-09-21 08:34
Not yet, I'm afraid. Feel free to provide a PR if you want to.

**Comment by Starsky-Type** [comment] 2021-09-27 05:45
I tried to modify the docker file for OO 6.4 version, successfully built the docker image but it still had the license warnning window, and the UI seemed not correct. Version 6.4 changed the code for license, need help too. @aleho

**Comment by aleho** [comment] 2021-09-27 07:51
I'm afraid I won't have time to investigate in the foreseeable future.

Either stay at the current version (should not be a problem for a personal setup) or pay for a license (you should do that if you're a company anyway).

I'm closing this as I'm aware of the new release and this technically is not a bug that I need to keep track of.

**Closed as completed by aleho** 2021-09-27 07:51 UTC
Labels: enhancement
