### ISSUE TITLE
New Version OnlyOffice 7.0

### ISSUE THREAD

**Issue by sebaxakerhtc** [aleho/onlyoffice-ce-docker-license#34] opened 2022-03-08 15:40 UTC
Hi. Thank you for this project!
After update app from Nextcloud it wants OnlyOffice 7.0 for the normal work of some new functions.
For example:
![1](https://user-images.githubusercontent.com/32651506/157271862-4dd23757-9478-4baf-a9d2-806755df865d.png)
![2](https://user-images.githubusercontent.com/32651506/157271884-90bc7ee6-7bc9-4a25-bff7-80630d44e2ec.png)

**Comment by aleho** [comment] 2022-03-08 18:47
If you want to provide a pull request to support / patch version 7, I'll be happy to review and merge it.

**Comment by sebaxakerhtc** [comment] 2022-03-08 18:52
> If you want to provide a pull request to support / patch version 7, I'll be happy to review and merge it.

Thank you for your reply.
Maybe if you provide info, what exactly you changed in version 6 - we can do it together.

**Comment by aleho** [comment] 2022-03-08 18:58
Have a look at the `.patch` files in this repository.

These patches are being applied to a git repository. For details on how this works you can see all steps needed (e.g. to reproduce it locally in a Linux container) in the `Dockerfile`.

**Comment by n-goncalves** [comment] 2022-03-24 10:23
I have managed to update OnlyOffice to 7.0.1 in my repository. (https://github.com/n-goncalves/onlyoffice-ce-docker-license). It removes the license restriction. However they have completely changed the mobile editor so I haven't tried to restore that. 

If you think that it's worth updating your repository, I can submit a pull request.

**Comment by aleho** [comment] 2022-03-24 11:55
Without restoring the mobile editor using a patched image makes no sense at all.

(Because even if the license check is successfull the features are still missing)

**Comment by n-goncalves** [comment] 2022-03-24 12:12
Fair enough, in my case I needed to get past the simultaneous connection limit so that's what I did. 
One could re-enable the mobile editor by changing the value returned by isSupportEditFeature, but you'd still end up with a crippled mobile editor without a toolbar so not worth it.

**Comment by lulzzz** [comment] 2022-05-01 14:24
https://help.nextcloud.com/t/onlyoffice-compiled-with-mobile-edit-back/79282/160

**Comment by soonic6** [comment] 2022-05-29 08:28
@n-goncalves  do you have n dockerhub repo for pulling your patched image?

**Comment by iamkhalidbashir** [comment] 2022-06-04 11:09
I think n-goncalves's repo should be merged with a new branch

**Comment by soonic6** [comment] 2022-06-05 07:17
> I think n-goncalves's repo should be merged with a new branch

really? i don't think so... the docker file is older than 12 month.

**Comment by beeant0512** [comment] 2022-06-05 08:47
@soonic6 I have already build a docker image using the srcripts, only webapps patch failed, and I have tried to open more than 20 files. It's OK!

the docker image： xbeeant/oo-unlimit:7.1.0.215

**Comment by soonic6** [comment] 2022-06-05 09:20
@beeant0512 
> ... only webapps patch failed...

what are the webapps in detail?

> the docker image： xbeeant/oo-unlimit:7.1.0.215

mobile wont work...

**Comment by beeant0512** [comment] 2022-06-05 09:58
@soonic6 web-apps.patch patch failed

**Comment by sebaxakerhtc** [comment] 2022-06-05 10:13
> https://help.nextcloud.com/t/onlyoffice-compiled-with-mobile-edit-back/79282/160

Works. Thank you

**Comment by beeant0512** [comment] 2022-06-06 03:29
@soonic6  try xbeeant/oo-unlimit:7.1.1.23

**Comment by soonic6** [comment] 2022-06-06 07:08
@beeant0512 
> @soonic6 try xbeeant/oo-unlimit:7.1.1.23

still without mobile editing.

**Comment by aleho** [comment] 2022-06-07 19:30
> @beeant0512
> still without mobile editing.

Exactly.

I'm sorry, because that's hours of work for a product I'm not going to use any more this will not be implemented in the foreseeable future.

**Closed as not planned by aleho** 2022-06-07 19:30 UTC
Labels: not an issue
